stages:
  - install_dependencies
  - build
  - test
  

install_dependencies:
  stage: install_dependencies
  image: node:14
  script:
    - npm install

build:
  stage: build
  image: node:14
  script:
    - npm run build

test:
  stage: test
  image: node:14
  script:
    - npm run test
